# Generated by Django 4.1.1 on 2022-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigurd', '0003_story_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
